function quote(value) {
  return JSON.stringify(value);
}

function safeTypeName(name) {
  const normalized = name.split(/[^A-Za-z0-9_$]+/).filter(Boolean)
    .map((part) => part[0].toUpperCase() + part.slice(1)).join("") || "StateMachine";
  return /^[A-Za-z_$]/.test(normalized) ? normalized : `_${normalized}`;
}

export function emitTypeScript(spec) {
  const typeName = safeTypeName(spec.name);
  const stateUnion = spec.states.map(quote).join(" | ");
  const eventUnion = [...new Set(spec.transitions.map((item) => item.event))].sort().map(quote).join(" | ") || "never";
  const guards = [...new Set(spec.transitions.map((item) => item.guard).filter(Boolean))].sort();
  const effects = [...new Set(spec.transitions.map((item) => item.effect).filter(Boolean))].sort();
  const entries = spec.states.map((state) => {
    const outgoing = spec.transitions.filter((item) => item.from === state);
    return `    ${quote(state)}: { ${outgoing.map((item) => `${quote(item.event)}: ${quote(item.to)}`).join(", ")} }`;
  });
  const guardFields = guards.map((name) => `    ${quote(name)}: (context: Context) => boolean | Promise<boolean>;`).join("\n");
  const effectFields = effects.map((name) => `    ${quote(name)}: (context: Context) => Context | void | Promise<Context | void>;`).join("\n");
  const transitionList = JSON.stringify(spec.transitions, null, 2).replace(/^/gm, "  ").trimStart();
  const guardRuntime = guards.length
    ? `  const guardName = "guard" in item && typeof item.guard === "string" ? item.guard : undefined;\n  if (guardName) {\n    const guard = handlers.guards[guardName];\n    if (typeof guard !== "function") throw new Error(\`Missing guard handler '\${guardName}'\`);\n    if (!(await guard(context))) throw new Error(\`Guard '\${guardName}' rejected transition\`);\n  }\n`
    : "";
  const effectRuntime = effects.length
    ? `  const effectName = "effect" in item && typeof item.effect === "string" ? item.effect : undefined;\n  if (effectName) {\n    const effect = handlers.effects[effectName];\n    if (typeof effect !== "function") throw new Error(\`Missing effect handler '\${effectName}'\`);\n    const result = await effect(context);\n    if (result !== undefined) nextContext = result;\n  }\n`
    : "";
  const binding = spec.binding ? `  binding: ${JSON.stringify(spec.binding)},\n` : "";
  const boundType = spec.binding
    ? `\nexport type ${typeName}Record = Record<string, unknown> & { ${quote(spec.binding.field)}: ${typeName}State };\n\nexport async function transition${typeName}Record<Context, RecordType extends ${typeName}Record>(record: RecordType, event: ${typeName}Event, context: Context, handlers: ${typeName}Handlers<Context>): Promise<{ state: ${typeName}State; context: Context; record: RecordType }> {\n  const result = await transition${typeName}(record[${quote(spec.binding.field)}], event, context, handlers);\n  return { ...result, record: { ...record, [${quote(spec.binding.field)}]: result.state } as RecordType };\n}\n`
    : "";

  return `// Generated by mermaid-spec. Do not edit.\n` +
    `export type ${typeName}State = ${stateUnion};\n` +
    `export type ${typeName}Event = ${eventUnion};\n\n` +
    `export interface ${typeName}Handlers<Context> {\n` +
    (guards.length ? `  guards: {\n${guardFields}\n  };\n` : `  guards?: Record<never, never>;\n`) +
    (effects.length ? `  effects: {\n${effectFields}\n  };\n` : `  effects?: Record<never, never>;\n`) +
    `}\n\n` +
    `export const ${typeName} = {\n` +
    binding +
    `  initial: ${quote(spec.initial)},\n` +
    `  terminal: ${JSON.stringify(spec.terminal)},\n` +
    `  transitions: {\n${entries.join(",\n")}\n  },\n` +
    `  transitionList: ${transitionList}\n` +
    `} as const;\n\n` +
    `export async function transition${typeName}<Context>(state: ${typeName}State, event: ${typeName}Event, context: Context, handlers: ${typeName}Handlers<Context>): Promise<{ state: ${typeName}State; context: Context }> {\n` +
    `  const item = ${typeName}.transitionList.find(candidate => candidate.from === state && candidate.event === event);\n` +
    `  if (!item) throw new Error(\`Invalid transition: \${state} --\${event}--> ?\`);\n` +
    guardRuntime +
    `  let nextContext = context;\n` +
    effectRuntime +
    `  return { state: item.to, context: nextContext };\n` +
    `}\n` +
    boundType;
}

export function emitJavaScript(spec) {
  const name = safeTypeName(spec.name);
  const runtimeImports = spec.binding ? "transition, transitionRecord" : "transition";
  return `// Generated by mermaid-spec. Do not edit.\n` +
    `import { ${runtimeImports} } from "mermaid-spec/runtime";\n\n` +
    `export const ${name} = ${JSON.stringify(spec, null, 2)};\n\n` +
    `export function transition${name}(state, event, context, handlers) {\n` +
    `  return transition(${name}, state, event, context, handlers);\n` +
    `}\n` +
    (spec.binding ? `\nexport function transition${name}Record(record, event, context, handlers) {\n  return transitionRecord(${name}, record, event, context, handlers);\n}\n` : "");
}
