const TS_TYPES = { uuid: "string", string: "string", text: "string", email: "string", datetime: "string", date: "string", int: "number", integer: "number", float: "number", boolean: "boolean", json: "unknown" };
const JSON_TYPES = { uuid: "string", string: "string", text: "string", email: "string", datetime: "string", date: "string", int: "integer", integer: "integer", float: "number", boolean: "boolean", json: "object" };
const SQL_TYPES = { uuid: "UUID", string: "VARCHAR(255)", text: "TEXT", email: "VARCHAR(320)", datetime: "TIMESTAMPTZ", date: "DATE", int: "INTEGER", integer: "INTEGER", float: "DOUBLE PRECISION", boolean: "BOOLEAN", json: "JSONB" };

export function modelTypeName(value) {
  const words = value
    .replace(/([a-z0-9])([A-Z])/g, "$1 $2")
    .split(/[^A-Za-z0-9]+/)
    .filter(Boolean);
  const normalized = words.map((part) => part[0].toUpperCase() + part.slice(1).toLowerCase()).join("");
  return normalized || "Model";
}

export function modelSqlName(value) {
  return value.replace(/([a-z0-9])([A-Z])/g, "$1_$2").replace(/[^A-Za-z0-9]+/g, "_").toLowerCase();
}

function sqlName(value) {
  return `"${modelSqlName(value)}"`;
}

function sqlLiteral(value) {
  if (typeof value === "string") return `'${value.replaceAll("'", "''")}'`;
  if (value === null) return "NULL";
  if (typeof value === "boolean") return value ? "TRUE" : "FALSE";
  return String(value);
}

function known(map, attribute) {
  const value = map[attribute.type.toLowerCase()];
  if (!value) throw new Error(`Unsupported primitive model type '${attribute.type}' on '${attribute.name}'`);
  return value;
}

function referencedEntity(model, attribute) {
  return model.entities.find((entity) => entity.name === attribute.type);
}

function tsType(model, attribute) {
  let value;
  if (attribute.enum) value = attribute.enum.map((item) => JSON.stringify(item)).join(" | ");
  else if (TS_TYPES[attribute.type.toLowerCase()]) value = known(TS_TYPES, attribute);
  else {
    const reference = referencedEntity(model, attribute);
    if (!reference) throw new Error(`Unknown model type '${attribute.type}' on '${attribute.name}'`);
    value = modelTypeName(reference.name);
  }
  if (attribute.array) value = attribute.enum ? `(${value})[]` : `${value}[]`;
  if (attribute.nullable) value += " | null";
  return value;
}

function scalarJsonSchema(model, attribute) {
  let schema;
  if (JSON_TYPES[attribute.type.toLowerCase()]) {
    const format = jsonFormat(attribute.type.toLowerCase());
    schema = { type: known(JSON_TYPES, attribute), ...(format ? { format } : {}) };
  } else {
    const reference = referencedEntity(model, attribute);
    if (!reference) throw new Error(`Unknown model type '${attribute.type}' on '${attribute.name}'`);
    schema = { $ref: `#/$defs/${modelTypeName(reference.name)}` };
  }
  if (attribute.enum) schema.enum = attribute.enum;
  for (const key of ["minimum", "maximum", "minLength", "maxLength", "pattern"]) {
    if (attribute[key] !== undefined) schema[key] = attribute[key];
  }
  return schema;
}

function jsonSchema(model, attribute) {
  const scalar = scalarJsonSchema(model, attribute);
  let schema = attribute.array
    ? { type: "array", items: scalar, ...(attribute.minItems !== undefined ? { minItems: attribute.minItems } : {}), ...(attribute.maxItems !== undefined ? { maxItems: attribute.maxItems } : {}) }
    : scalar;
  if (attribute.nullable) schema = { anyOf: [schema, { type: "null" }] };
  if (attribute.default !== undefined) schema.default = attribute.default;
  return schema;
}

function jsonFormat(type) {
  if (type === "uuid" || type === "email" || type === "date") return type;
  if (type === "datetime") return "date-time";
  return undefined;
}

export function emitModelTypeScript(model) {
  return `// Generated by mermaid-spec. Do not edit.\n\n` + model.entities.map((entity) => {
    const fields = entity.attributes.map((attribute) => `  ${JSON.stringify(attribute.name)}${attribute.optional ? "?" : ""}: ${tsType(model, attribute)};`).join("\n");
    return `export interface ${modelTypeName(entity.name)} {\n${fields}\n}`;
  }).join("\n\n") + "\n";
}

export function emitJsonSchema(model) {
  const defs = {};
  for (const entity of model.entities) {
    const properties = {};
    for (const attribute of entity.attributes) {
      properties[attribute.name] = jsonSchema(model, attribute);
    }
    defs[modelTypeName(entity.name)] = { type: "object", additionalProperties: false, properties, required: entity.attributes.filter((item) => !item.optional).map((item) => item.name) };
  }
  return `${JSON.stringify({ $schema: "https://json-schema.org/draft/2020-12/schema", $defs: defs }, null, 2)}\n`;
}

export function emitSql(model) {
  const foreignKeys = [];
  const tables = model.entities.filter((entity) => (entity.role ?? "table") === "table").map((entity) => {
    if (!entity.attributes.length) throw new Error(`Entity '${entity.name}' must declare at least one attribute for SQL generation`);
    const primaryKeys = entity.attributes.filter((attribute) => attribute.keys.includes("PK"));
    const columns = entity.attributes.map((attribute) => {
      const reference = referencedEntity(model, attribute);
      let columnType = reference ? "JSONB" : known(SQL_TYPES, attribute);
      if (attribute.array && !reference) columnType += "[]";
      const constraints = [];
      if (!attribute.optional && !attribute.nullable) constraints.push("NOT NULL");
      if (primaryKeys.length === 1 && attribute.keys.includes("PK")) constraints.push("PRIMARY KEY");
      if (attribute.keys.includes("UK")) constraints.push("UNIQUE");
      if (attribute.default !== undefined) constraints.push(`DEFAULT ${sqlLiteral(attribute.default)}`);
      if (attribute.enum) constraints.push(`CHECK (${sqlName(attribute.name)} IN (${attribute.enum.map(sqlLiteral).join(", ")}))`);
      if (attribute.minimum !== undefined) constraints.push(`CHECK (${sqlName(attribute.name)} >= ${attribute.minimum})`);
      if (attribute.maximum !== undefined) constraints.push(`CHECK (${sqlName(attribute.name)} <= ${attribute.maximum})`);
      if (attribute.minLength !== undefined) constraints.push(`CHECK (char_length(${sqlName(attribute.name)}) >= ${attribute.minLength})`);
      if (attribute.maxLength !== undefined) constraints.push(`CHECK (char_length(${sqlName(attribute.name)}) <= ${attribute.maxLength})`);
      if (attribute.minItems !== undefined) constraints.push(`CHECK (cardinality(${sqlName(attribute.name)}) >= ${attribute.minItems})`);
      if (attribute.maxItems !== undefined) constraints.push(`CHECK (cardinality(${sqlName(attribute.name)}) <= ${attribute.maxItems})`);
      if (attribute.keys.includes("FK")) {
        const prefix = modelSqlName(attribute.name).replace(/_?id$/, "");
        const target = model.entities.find((candidate) => modelSqlName(candidate.name) === prefix);
        const targetKeys = target?.attributes.filter((candidate) => candidate.keys.includes("PK")) ?? [];
        if (!target || (target.role ?? "table") !== "table" || targetKeys.length !== 1) throw new Error(`Cannot resolve foreign key '${entity.name}.${attribute.name}' to a single-column primary key`);
        const [primaryKey] = targetKeys;
        if (known(SQL_TYPES, attribute) !== known(SQL_TYPES, primaryKey)) throw new Error(`Foreign key '${entity.name}.${attribute.name}' type does not match '${target.name}.${primaryKey.name}'`);
        foreignKeys.push(`ALTER TABLE ${sqlName(entity.name)} ADD FOREIGN KEY (${sqlName(attribute.name)}) REFERENCES ${sqlName(target.name)}(${sqlName(primaryKey.name)});`);
      }
      return `  ${sqlName(attribute.name)} ${columnType}${constraints.length ? ` ${constraints.join(" ")}` : ""}`;
    });
    if (primaryKeys.length > 1) columns.push(`  PRIMARY KEY (${primaryKeys.map((attribute) => sqlName(attribute.name)).join(", ")})`);
    return `CREATE TABLE ${sqlName(entity.name)} (\n${columns.join(",\n")}\n);`;
  });
  return [...tables, ...foreignKeys].join("\n\n") + "\n";
}
